//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DimigoGameLast.rc
//
#define IDB_SPIT                        105
#define IDB_DINGDING_STANDING           106
#define IDB_DINGDING_CHEERING           107
#define IDB_FINISH_FLAG                 108
#define IDB_COCO_CHEERING               109
#define IDB_COCO_STANDING               110
#define IDB_COCO_WON                    111
#define IDB_DINGDING_WON                112
#define IDB_READY                       114
#define IDB_START                       115
#define IDB_COCO_DISK                   116
#define IDB_COCO_DISK1                  116
#define IDB_DINGDING_DISK               117
#define IDB_DISK_BACKGROUND             118
#define IDB_COCO_TURN                   119
#define IDB_DINGDING_TURN               120
#define IDB_NOW_BLOW                    121
#define IDB_COCO_THROWING               122
#define IDB_DINGDING_THROWING           123
#define IDB_SCORE_BOARD                 124
#define IDB_DISK_SHADOW                 125
#define IDB_BITMAP1                     126
#define IDB_SKY_BACKGROUND              126
#define IDB_STRING                      127
#define IDB_PULL_BACKGROUND             128
#define IDB_COCO_FLAG                   129
#define IDB_DINGDING_FLAG               130
#define IDB_DISK_HELP                   131
#define IDB_PULL_HELP                   132
#define IDB_DISK_LOGO                   133
#define IDB_PULL_LOGO                   134
#define IDB_COCO_DISK2                  135
#define IDB_COCO_DISK3                  136
#define IDB_BITMAP4                     137
#define IDB_COCO_DISK4                  137
#define IDB_DINGDING_DISK1              138
#define IDB_DINGDING_DISK2              139
#define IDB_DINGDING_DISK3              140
#define IDB_BITMAP6                     141
#define IDB_DINGDING_DISK4              141
#define IDB_DISK_CROSSED_LINE           142
#define IDB_BITMAP3                     143
#define IDB_DISK_LINE                   143
#define IDB_BITMAP2                     144
#define IDB_NO_MENT                     144
#define IDB_COCO_CRYING                 145
#define IDB_BITMAP7                     146
#define IDB_DINGDING_CRYING             146
#define IDB_KEY_1                       147
#define IDB_KEY_2                       148
#define IDB_BITMAP9                     149
#define IDB_KEY_3                       149
#define IDB_KEY_7                       150
#define IDB_KEY_8                       151
#define IDB_KEY_9                       152
#define IDB_BITMAP5                     153
#define IDB_OK                          153
#define IDB_DINGDING_DANCE_DOWN         154
#define IDB_DINGDING_DANCE_LEFT         155
#define IDB_DINGDING_DANCE_RIGHT        156
#define IDB_DINGDING_DANCE_UP           157
#define IDB_COCO_DANCE_DOWN             158
#define IDB_COCO_DANCE_LEFT             159
#define IDB_COCO_DANCE_RIGHT            160
#define IDB_BITMAP13                    161
#define IDB_COCO_DANCE_UP               161
#define IDB_BITMAP8                     162
#define IDB_COCO_STANDING_DARK          162
#define IDB_DINGDING_STANDING_DARK      163
#define IDB_DANCE_BACKGROUND            164
#define IDB_DANCE_BACKGROUND_LEFT       165
#define IDB_BITMAP12                    166
#define IDB_DANCE_BACKGROUND_RIGHT      166
#define IDB_BITMAP10                    167
#define IDB_WRONG                       167
#define IDB_PROGRESS_0                  168
#define IDB_PROGRESS_1                  169
#define IDB_PROGRESS_2                  170
#define IDB_PROGRESS_3                  171
#define IDB_PROGRESS_4                  172
#define IDB_PROGRESS_5                  173
#define IDB_PROGRESS_6                  174
#define IDB_PROGRESS_7                  175
#define IDB_PROGRESS_8                  176
#define IDB_PROGRESS_9                  177
#define IDB_BITMAP23                    178
#define IDB_PROGRESS_10                 178
#define IDB_BITMAP11                    179
#define IDB_TEACHER_HELP                179
#define IDB_BITMAP14                    180
#define IDB_STORY_TIMETABLE             180
#define IDB_BITMAP15                    181
#define IDB_STORY_FIRST                 181
#define IDB_STORY_COCO_WIN              182
#define IDB_BITMAP17                    183
#define IDB_STORY_DINGDING_WIN          183
#define IDB_DANCE_HELP                  184
#define IDB_BITMAP18                    185
#define IDB_DANCE_LOGO                  185
#define IDB_STORY_COCO_CLEAN            186
#define IDB_BITMAP19                    187
#define IDB_STORY_DINGDING_CLEAN        187
#define IDB_BITMAP16                    188
#define IDB_FINAL_RESULT_BACKGROUND     188

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        189
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
